[MERGE] 1주차 스택과 큐
5jisoo/Algorithm-Study pull request #4
Opened 2023-01-05 11:02 UTC by 5jisoo

2023-01-08 03:16 UTC, dudrhy12 approved these changes
[코드리뷰]
1. 시간 초과 : 사전기술을 각각 리스트 사용해서 했군요.. 제가 1개의 리스트에 넣어서 하려다 시간초과나서 그냥 카운트로 방향을 틀었답니다.
2. 리스트 변수명이 st_LR과 st_SK에서 st인 이유가 궁금해요
3. 숫자 기술 : 숫자 기술(line8)은 저도 처음엔 isdigit 함수로 했지만 if문의 마지막에 else에 넣어도 잘 돌아가더라구요. 
4. 기술 입력 : line6에 list로 안받고 그냥 입력 받아도 가능하더라요.

2023-01-08 11:54 UTC, codeJiwon reviewed
2로 나눈 나머지를 이용해서 길이가 홀수일 때 "NO"가 출력되도록 짜는 방법은 생각 못했어서 신선해요! 
근데 16, 17번째 줄에 elif로 안묶고 두줄로 else, if로 나눠서 짜신 이유가 궁금해요

2023-01-09 08:25 UTC, Jjinyshin requested changes

2023-01-09 08:25 UTC, Jinyshin commented on 23-winter-algorithm/stack_queue/baekjoon/2161/오지수.py
> +# queue = [ i for i in range(1, n+1)]
오 굿 list comprehension 저도 이제 이거 써야겠어요

2023-01-09 08:25 UTC, Jinyshin commented on 23-winter-algorithm/stack_queue/baekjoon/2161/오지수.py
> +    print(queue.pop(0))     # 제일 위에 있는 카드 버리기
pop이 리턴을 해주니까  이걸 바로 프린트해주는게 따로 변수선언하는것보다 더 낫겠군요👍

2023-01-09 08:25 UTC, Jinyshin commented on 23-winter-algorithm/stack_queue/baekjoon/11866/오지수.py
> +    point = (point + (k - 1)) % n   # 식 도출 가능
이 식은 어떻게 도출했나요??

2023-01-09 08:25 UTC, Jjinyshin commented on 23-winter-algorithm/stack_queue/baekjoon/11866/오지수.py
> +    point = (point + (k - 1)) % n   # 식 도출 가능
자연스럽게 도출되는군요..

2023-01-09 08:26 UTC, Jjinyshin approved these changes

2023-01-09 13:04 UTC, codeJiwon approved these changes

2023-01-09 13:32 UTC, merged

2023-01-11 04:10 UTC, 5jisoo commented
> [코드리뷰] 25497번
> 
> 1. 시간 초과 : 사전기술을 각각 리스트 사용해서 했군요.. 제가 1개의 리스트에 넣어서 하려다 시간초과나서 그냥 카운트로 방향을 틀었답니다.
-> 아 메모리에선 카운트가 더 좋아보이긴 하네요
> 2. 리스트 변수명이 st_LR과 st_SK에서 st인 이유가 궁금해요
-> stack이란 뜻입니다~
> 3. 숫자 기술 : 숫자 기술(line8)은 저도 처음엔 isdigit 함수로 했지만 if문의 마지막에 else에 넣어도 잘 돌아가더라구요.
-> 아 애초에 input으로 숫자, 알파벳 이외의 반례가 주어지지 않나봐요 확인했습니다~
> 4. 기술 입력 : line6에 list로 안받고 그냥 입력 받아도 가능하더라요.
-> 반복문 돌릴려고 list에 넣긴 했는데 그런가요?? 테스트코드 돌려보겠습니닷

2023-01-11 04:49 UTC, 5jisoo commented
> 2로 나눈 나머지를 이용해서 길이가 홀수일 때 "NO"가 출력되도록 짜는 방법은 생각 못했어서 신선해요! 근데 16, 17번째 줄에 elif로 안묶고 두줄로 else, if로 나눠서 짜신 이유가 궁금해요

사실 큰 의미 없고 elif 쓰는게 맞죠..ㅎㅎ  코드를 짰을때의 심정을 되짚어보자면.. st가 없는 경우를 구조적으로 더 깔끔하게 보고싶었던 것으로 추정됩니다